name: Containers
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - alpine: edge
            tag: 81
            php: 81
          - alpine: 3.15
            tag: 80
            php: 8
          - alpine: 3.15
            tag: 74
            php: 7
          - alpine: 3.12
            tag: 73
            php: 7

    name: Tag ${{ matrix.tag }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          REGISTRY: ghcr.io
          OWNER: flat3
          IMAGE_NAME: lodata
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/flat3/lodata:${{ matrix.tag }}
          build-args: |
            ALPINE=${{ matrix.alpine }}
            PHP=${{ matrix.php }}
